### ISSUE TITLE
Support for ignoring certain package namespaces?

### ISSUE THREAD

**Issue by ZacSweers** [xfumihiro/ViewInspector#1]
I get the following error due to a conflict with an external library:

```
Error:(51, 18) error: onDraw(Canvas) in ProbeProxy$com_afollestad_materialdialogs_internal_MDRootLayout cannot override onDraw(Canvas) in MDRootLayout
attempting to assign weaker access privileges; was public
```

Obviously it would be nice to just have a fix if it's a bug, but would be nice to be able to skip namespaces in the meantime

**Comment by xfumihiro** [comment]
I wonder if it's a bad idea to assign public access privileges to all proxies. That's the easiest solution.
