### ISSUE TITLE
Error:D:\workspace\leying\src\main\AndroidManifest.xml (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by ihrthk** [xfumihiro/ViewInspector#12]
Don't support sourceSets,main config.

**Comment by xfumihiro** [comment]
Can you share the build.gradle file & your project structure? It should work just fine.

**Comment by ihrthk** [comment]
buildscript {
    repositories {
//        jcenter{
//            url 'http://jcenter.bintray.com'
//        }
        maven{
            url 'http://repo1.maven.org/maven2/'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.2.1'
//        classpath 'com.github.xfumihiro.view-inspector:view-inspector-plugin:0.1.1'
    }
}

plugins {
    id "me.zhangls.mulchannel" version "0.0.2"
}
allprojects {
    repositories {
//        jcenter{
//            url 'http://jcenter.bintray.com'
//        }
        maven{
            url 'http://repo1.maven.org/maven2/'
        }
    }
}

apply from: './my.gradle'
apply plugin: 'com.android.application'
apply plugin: 'com.getkeepsafe.dexcount'
//apply plugin: 'view-inspector'

android {
    compileSdkVersion 22
    buildToolsVersion "23.0.0"

//    useLibrary 'org.apache.http.legacy'

```
defaultConfig {
    minSdkVersion 11
    targetSdkVersion 21
}

sourceSets {
    main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['src']
        resources.srcDirs = ['src']
        aidl.srcDirs = ['src']
        renderscript.srcDirs = ['src']
        res.srcDirs = ['res']
        assets.srcDirs = ['assets']
        jniLibs.srcDirs = ['libs']
    }

    // Move the tests to tests/java, tests/res, etc...
    instrumentTest.setRoot('tests')

    // Move the build types to build-types/<type>
    // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
    // This moves them out of them default location under src/<type>/... which would
    // conflict with src/ being used by the main source set.
    // Adding new build types or product flavors should be accompanied
    // by a similar customization.
    debug.setRoot('build-types/debug')
    release.setRoot('build-types/release')
}

lintOptions {
    abortOnError false
}



packagingOptions {
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
}
```

}

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile project(':library:load-more')
    compile project(':library:ptr-lib')
    compile project(':library:MainLibs')
    compile project(':library:OneKeyShare')
    compile 'com.squareup.picasso:picasso:2.5.2'
}
