### ISSUE TITLE
Resources$NotFoundException when logging is enabled

### ISSUE THREAD

**Issue by artemdanylenko** [xfumihiro/ViewInspector#33]
0:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime: android.content.res.Resources$NotFoundException: Unable to find resource ID #0xc00200
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at android.content.res.Resources.getResourceName(Resources.java:3216)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at view_inspector.util.ViewUtil.getViewId(ViewUtil.java:12)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at view_inspector.util.ViewUtil.getSimpleViewId(ViewUtil.java:16)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at view_inspector.probe.util.LogUtil.logRequestLayout(LogUtil.java:116)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.requestLayout(ViewInspectorInterceptor.java:217)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at com.skype.android.app.view_inspector.ProbeProxy$android_widget_RelativeLayout.requestLayout(ProbeProxy$android_widget_RelativeLayout.java:64)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at android.view.View.setFlags(View.java:10641)
10-28 20:09:14.727 17090-17090/com.skype.android.app E/AndroidRuntime:     at android.view.View.setVisibility(View.java:7136)

should be enough just to wrap in try/catch as it looks like API bug https://code.google.com/p/android/issues/detail?id=55965

**Comment by xfumihiro** [comment]
Thanks!
