### ISSUE TITLE
Crash on Probe Measures when layout contains FitWindowsLinearLayout

### ISSUE THREAD

**Issue by artemdanylenko** [xfumihiro/ViewInspector#35]
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime: java.lang.ClassCastException: android.support.v7.internal.widget.FitWindowsLinearLayout cannot be cast to view_inspector.probe.ViewProxy
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at view_inspector.probe.Interceptor.invokeForceLayout(Interceptor.java:139)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.forceLayoutRecursive(ViewInspectorInterceptor.java:242)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.forceLayoutRecursive(ViewInspectorInterceptor.java:249)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.requestLayout(ViewInspectorInterceptor.java:226)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at com.skype.android.app.view_inspector.ProbeProxy$android_widget_FrameLayout.requestLayout(ProbeProxy$android_widget_FrameLayout.java:64)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at android.view.View.requestLayout(View.java:18530)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at android.view.View.requestLayout(View.java:18530)
10-28 22:02:32.659 11057-11057/com.skype.android.app E/AndroidRuntime:     at android.view.View.requestLayout(View.java:18530)

**Comment by xfumihiro** [comment]
@asdanilenk I tried put a FitWindowsLinearLayout inside sample app's layout and it didn't crash. Can you share more details?

**Comment by artemdanylenko** [comment]
I will try to get full trace a bit later

**Comment by xfumihiro** [comment]
I'm able to reproduce the issue with the Stock Navigation Drawer Activity template.
Will close this soon.
