### ISSUE TITLE
0.1.4 compile failed

### ISSUE THREAD

**Issue by ihrthk** [xfumihiro/ViewInspector#36]
D:\workspace\leying\build\generated\source\view-inspector\debug\com\levp\leying\view_inspector\ProbeProxy$android_widget_requestFocus.java
Error:(8, 22) 错误: 找不到符号
符号:   类 requestFocus
位置: 程序包 android.widget
Error:(9, 67) 错误: 找不到符号
符号: 类 requestFocus
Error:(20, 30) 错误: 不兼容的类型: ProbeProxy$android_widget_requestFocus无法转换为View
Error:(23, 7) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(27, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(31, 29) 错误: 不兼容的类型: ProbeProxy$android_widget_requestFocus无法转换为View
Error:(34, 7) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(38, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(42, 25) 错误: 不兼容的类型: ProbeProxy$android_widget_requestFocus无法转换为View
Error:(45, 7) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(49, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(53, 27) 错误: 不兼容的类型: ProbeProxy$android_widget_requestFocus无法转换为View
Error:(56, 7) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(60, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(64, 34) 错误: 不兼容的类型: ProbeProxy$android_widget_requestFocus无法转换为View
Error:(67, 7) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(71, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(75, 32) 错误: 不兼容的类型: ProbeProxy$android_widget_requestFocus无法转换为View
Error:(78, 7) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(82, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus
Error:(85, 5) 错误: 找不到符号
符号:   变量 super
位置: 类 ProbeProxy$android_widget_requestFocus

**Comment by xfumihiro** [comment]
Duplicate of #31
