### ISSUE TITLE
貌似不能与LeakCanary兼容

### ISSUE THREAD

**Issue by peacepassion** [xfumihiro/ViewInspector#53]
引入了LeakCanay后，再引入ViewInspector,会在build阶段报一个：  
Error:(9, 97) 错误: 无法从最终DisplayLeakConnectorView进行继承

**Comment by xfumihiro** [comment]
Duplicate of #14

**Comment by xfumihiro** [comment]
To work with LeakCanary:

```
viewInspector {
  excludePackages = ['com.squareup.leakcanary.internal']
}
```

**Comment by peacepassion** [comment]
@xfumihiro 明白了。非常感谢。这个库很赞！！！很强大。
