### ISSUE TITLE
how can I debug Plugin code?

### ISSUE THREAD

**Issue by kissazi2** [xfumihiro/ViewInspector#57]
as Title descript。I Have googling a lot ,but can't find a good way to solved this problem.

**Comment by xfumihiro** [comment]
just run gradle with --debug

**Comment by kissazi2** [comment]
I run gradle assembleDebug --debug in sample project,but still can't hit the breakpoint in groovy

**Comment by xfumihiro** [comment]
That only shows debug log messages. I don't know if you can debug it like in java. Try ask it in stackoverflow or Gradle's forum. I will close this issue as this isn't related to the project, but feel free to share found infos if you like! :smiley:
